### ISSUE TITLE
Avoid floating point arithmetic

### ISSUE THREAD

**Issue by smk762** [smk762/mmbot_qt#19]
Background: 
- https://bitcointalk.org/index.php?topic=13837.0
- https://github.com/KomodoPlatform/atomicDEX-QT/issues/2#issue-533638047

For precision in trades, we should favour rational numbers, though for table display some rounding is good.

https://docs.python.org/3/library/decimal.html

**Comment by smk762** [comment]
Binance seems to avoid this using a "step size" to force trade amounts and prices to a set precision.

**Comment by smk762** [comment]
Binance rounding to step and lot increments is operational. Perhaps simplest solution is to make MM2 orders conform to the same?

**Comment by tonymorony** [comment]
Imo bot should be abstracted of such exchanges APIs specifics. 
MM2 works with rational numbers https://developers.komodoplatform.com/basic-docs/atomicdex/atomicdex-api.html#note-about-rational-number-type

**Comment by smk762** [comment]
I read that, but I think I was overcomplicating it in my mind assuming the rat_num would need to be converted. Looking again, I see it can be grabbed from orderbook output method and used as an input for buy/sell commands. Should be simple enough to change code accordingly.
Is there any potential case where I'll need to convert a float to this format (or vice versa)?

**Comment by smk762** [comment]
testing iterative volume reduction from max, and awaiting upstream mm2 API tweaks
