### ISSUE TITLE
Separate GUI and Bot logic (make bot API)

### ISSUE THREAD

**Issue by tonymorony** [smk762/mmbot_qt#20]
It would be great to separate mm2bot GUI and bot logic API for easier scaling / modifications and clearer codebase + in such case any other GUI will be able to use bot logic

**Comment by smk762** [comment]
initial version of this is done in https://github.com/smk762/mmbot_api 
Ongoing improvements pending feedback. 
Methods able to be performed directly with mm2 API are not included, but may be useful for 3rd party apps.

**Comment by smk762** [comment]
closing, updates to be requested in https://github.com/smk762/mmbot_api/issues
